# make it explicit that we favor the new container-based travis workers

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: xenial

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # Linux environment to test scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    -  python: 3.7
       env: CHECK_WARNINGS="true"
       if: type = cron OR commit_message =~ /\[scipy-dev\]/

install: source build_tools/travis/install.sh
script:
  - bash build_tools/travis/test_script.sh
  - bash build_tools/travis/test_docs.sh
  - bash build_tools/travis/test_pytest_soft_dependency.sh
after_success: source build_tools/travis/after_success.sh
 
